[theme]
primaryColor = "#e50914"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false